//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WU15.AlltOchMer.Web.test
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainCategoryNorway
    {
        public int id { get; set; }
        public string ProductName { get; set; }
        public Nullable<System.DateTime> PriceListName { get; set; }
        public int Category_Id { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Name { get; set; }
        public int LanguageId { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> VAT { get; set; }
    }
}
