//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WU15.AlltOchMer.Web.test
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlltOchMerEntities1 : DbContext
    {
        public AlltOchMerEntities1()
            : base("name=AlltOchMerEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cart> Cart { get; set; }
        public virtual DbSet<CartProduct> CartProduct { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<CategoryName> CategoryName { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<PriceList> PriceList { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductCategory> ProductCategory { get; set; }
        public virtual DbSet<ProductDescription> ProductDescription { get; set; }
        public virtual DbSet<ProductPriceList> ProductPriceList { get; set; }
        public virtual DbSet<supplier> supplier { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<VAT> VAT { get; set; }
        public virtual DbSet<CartProductSweden> CartProductSweden { get; set; }
        public virtual DbSet<DanishMainCategory> DanishMainCategory { get; set; }
        public virtual DbSet<MainCategoryDanmark> MainCategoryDanmark { get; set; }
        public virtual DbSet<MainCategoryNorway> MainCategoryNorway { get; set; }
        public virtual DbSet<NorwegianMainCategory> NorwegianMainCategory { get; set; }
        public virtual DbSet<ProductDk> ProductDk { get; set; }
        public virtual DbSet<ProductNo> ProductNo { get; set; }
        public virtual DbSet<ProductSe> ProductSe { get; set; }
        public virtual DbSet<Subcategories> Subcategories { get; set; }
        public virtual DbSet<SwedishMainCategory> SwedishMainCategory { get; set; }
        public virtual DbSet<SwedishSubcategory> SwedishSubcategory { get; set; }
    }
}
