//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WU15.AlltOchMer.Web.test
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSe
    {
        public int id { get; set; }
        public string name { get; set; }
        public int CategoryId { get; set; }
        public string Description { get; set; }
        public string ArticleNumber { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
