//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WU15.AlltOchMer.Web.test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subcategories
    {
        public Nullable<int> Categoryid { get; set; }
        public string Name { get; set; }
        public int Category_Id { get; set; }
        public string MainCategory { get; set; }
        public Nullable<int> Id { get; set; }
    }
}
